version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: redis
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: bundled:0
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: production
  sidekiq:
    image: bundled:0
    volumes:
      - .:/myapp
    command: 'bundle exec sidekiq'
    depends_on:
      - web
      - redis
    environment:
      RAILS_ENV: production
